// Location data for Telangana and Andhra Pradesh.
// Structure: { state: { district: [mandals...] } }
// Values are always in English regardless of form language.

export const locations = {
  Telangana: {
    "Adilabad": [
        "Adilabad",
        "Bheempur",
        "Bhainsa",
        "Boath",
        "Jainad",
        "Kerameri",
        "Narnoor",
        "Tamsi",
        "Utnoor"
    ],
    "Bhadradri Kothagudem": [
        "Aswapuram",
        "Bhadrachalam",
        "Burgampadu",
        "Charla",
        "Dummugudem",
        "Kothagudem",
        "Kukunoor",
        "Mulakalapalli",
        "Palvancha",
        "Sujathanagar",
        "Tekulapalli",
        "Yellandu"
    ],
    "Hyderabad": [
        "Ameerpet",
        "Amberpet",
        "Asifnagar",
        "Bahadurpura",
        "Bandlaguda",
        "Charminar",
        "Golconda",
        "Himayatnagar",
        "Khairatabad",
        "Musheerabad",
        "Nampally",
        "Saidabad",
        "Sanathnagar",
        "Secunderabad",
        "Shaikpet",
        "Trimulgherry"
    ],
    "Jagtial": [
        "Bheemgal",
        "Buggaram",
        "Dharmapuri",
        "Gollapalli",
        "Jagtial",
        "Kathalapur",
        "Koratla",
        "Mallial",
        "Medipalli",
        "Metagudem",
        "Pegadapalli",
        "Raikal",
        "Sarangapur",
        "Velgatoor"
    ],
    "Jangaon": [
        "Bachannapet",
        "Cherial",
        "Devaruppula",
        "Ghanpur Station",
        "Jangaon",
        "Kodakandla",
        "Lingalaghanpur",
        "Narmetta",
        "Palakurthi",
        "Raghunathpalle",
        "Tharigoppula",
        "Zaffergadh"
    ],
    "Jayashankar Bhupalpally": [
        "Bhupalpalle",
        "Chityal",
        "Ghanpur",
        "Kataram",
        "Mahadevpur",
        "Maha Mutharam",
        "Mogullapalle",
        "Palimela",
        "Regonda",
        "Raghunathapalle",
        "Tekumatla"
    ],
    "Jogulamba Gadwal": [
        "Alampur",
        "Dharur",
        "Dowlapur",
        "Gadwal",
        "Gattu",
        "Itikyala",
        "Kalakastala",
        "Maldakal",
        "Manopad",
        "Nagarkurnool",
        "Peadabahal",
        "Rajapet",
        "Waddepalle"
    ],
    "Kamareddy": [
        "Banswada",
        "Bhiknoor",
        "Bichkunda",
        "Dudhgaon",
        "Jukkal",
        "Kamareddy",
        "Kangti",
        "Machareddy",
        "Madnoor",
        "Nizamsagar",
        "Pitlam",
        "Regode",
        "Tadwai",
        "Yellareddy"
    ],
    "Karimnagar": [
        "Chigurumamidi",
        "Gangadhara",
        "Huzurabad",
        "Jammikunta",
        "Karimnagar",
        "Kothapalli",
        "Manakondur",
        "Mallial",
        "Peddapalli",
        "Ramadugu",
        "Sarangapur",
        "Sultanabad",
        "Thimmapur",
        "Vemulawada"
    ],
    "Khammam": [
        "Aswaraopeta",
        "Bayyaram",
        "Chintakani",
        "Dammapeta",
        "Enkur",
        "Julurpadu",
        "Kallur",
        "Kamepalli",
        "Khammam Rural",
        "Khammam Urban",
        "Konijerla",
        "Kothagudem",
        "Madhira",
        "Mudigonda",
        "Palair",
        "Penuballi",
        "Sathupalli",
        "Tallada",
        "Thirumalayapalem",
        "Vemsoor",
        "Wyra"
    ],
    "Komaram Bheem Asifabad": [
        "Asifabad",
        "Bejjur",
        "Chintalamanepalli",
        "Dahegaon",
        "Jainoor",
        "Kagaznagar",
        "Kerameri",
        "Khanapur",
        "Koutala",
        "Penchikalpet",
        "Rebbena",
        "Sirpur U",
        "Tiryani",
        "Wankidi"
    ],
    "Mahabubabad": [
        "Bayyaram",
        "Dornakal",
        "Gudur",
        "Inugurthy",
        "Kesamudram",
        "Kuravi",
        "Mahabubabad",
        "Maripeda",
        "Mothey",
        "Narsimhulapet",
        "Nellikudur",
        "Palakurthy",
        "Peddavangara",
        "Thorrur"
    ],
    "Mahabubnagar": [
        "Balanagar",
        "Bhoothpur",
        "Devarakadra",
        "Devarkondal",
        "Farooqnagar",
        "Gandeed",
        "Hanwada",
        "Jadcherla",
        "Kodangal",
        "Kothakota",
        "Mahabubnagar",
        "Midjil",
        "Moosapet",
        "Nawabpet",
        "Pangal",
        "Rajapur",
        "Shadnagar",
        "Talakondapalle",
        "Urkondapeta"
    ],
    "Mancherial": [
        "Bellampalli",
        "Bheemaram",
        "Chennur",
        "Dandepalli",
        "Hajipur",
        "Jaipur",
        "Jannaram",
        "Kasipet",
        "Kotapalli",
        "Luxettipet",
        "Mancherial",
        "Naspur",
        "Rajura",
        "Vemanpalli"
    ],
    "Medak": [
        "Alladurg",
        "Chinna Kodur",
        "Doultabad",
        "Havelighanpur",
        "Kangti",
        "Kaudipalli",
        "Kulcharam",
        "Medak",
        "Nagsanpalli",
        "Narayankhed",
        "Papannapet",
        "Ramayampet",
        "Sadasivapet",
        "Shankarampet",
        "Shivampet",
        "Tekmal",
        "Toguta"
    ],
    "Medchal Malkajgiri": [
        "Alwal",
        "Bachupally",
        "Balapur",
        "Dammaiguda",
        "Ghatkesar",
        "Kapra",
        "Keesara",
        "Kukatpally",
        "Malkajgiri",
        "Medchal",
        "Miyapur",
        "Mulugu",
        "Qutubullapur",
        "Rajbakul",
        "Secunderabad",
        "Shamirpet",
        "Uppal"
    ],
    "Mulugu": [
        "Eturnagaram",
        "Govindaraopet",
        "Jayashankar",
        "Kannaigudem",
        "Mangapet",
        "Mulugu",
        "Pasra",
        "Tadvai",
        "Venkatapur"
    ],
    "Nagarkurnool": [
        "Achampet",
        "Balmoor",
        "Bijinepalli",
        "Chinthalapalle",
        "Devarkadra",
        "Kalwakurthy",
        "Kollapur",
        "Nagarkurnool",
        "Nallabandakal",
        "Padra",
        "Pebberu",
        "Telkapally",
        "Urkonda",
        "Vangoor"
    ],
    "Nalgonda": [
        "Adavidevulapally",
        "Anumula",
        "Chandur",
        "Chityala",
        "Devarakonda",
        "Dameracherla",
        "Gurrampode",
        "Kattangoor",
        "Kethepally",
        "Munugode",
        "Nalgonda",
        "Nampally",
        "Narketpally",
        "Nidamanur",
        "Peddavura",
        "Thipparthy",
        "Tripuraram"
    ],
    "Narayanpet": [
        "Dameracherla",
        "Kodangal",
        "Kosgi",
        "Maddur",
        "Maganoor",
        "Makthal",
        "Narayanpet",
        "Pebberu",
        "Utkoor"
    ],
    "Nirmal": [
        "Bhainsa",
        "Dasturabad",
        "Dilawarpur",
        "Khanapur",
        "Kuntala",
        "Laxmanchanda",
        "Mamada",
        "Mudhole",
        "Narsapur",
        "Nirmal",
        "Pochera",
        "Sarangapur"
    ],
    "Nizamabad": [
        "Bheemgal",
        "Bodhan",
        "Chandur",
        "Dichpalli",
        "Jakranpalle",
        "Kammarpalle",
        "Khanderaopet",
        "Kotagiri",
        "Maklur",
        "Mendora",
        "Mupkal",
        "Nandipet",
        "Nizamabad Rural",
        "Nizamabad Urban",
        "Renjal",
        "Sirikonda",
        "Varni",
        "Yedapalli"
    ],
    "Peddapalli": [
        "Dharmaram",
        "Elkathurthy",
        "Geetaram",
        "Julapalli",
        "Kamanpur",
        "Kothapalli",
        "Manthani",
        "Mutharam",
        "Odela",
        "Palimela",
        "Peddapalli",
        "Ramagundam",
        "Sultanabad"
    ],
    "Rajanna Sircilla": [
        "Chandurthi",
        "Gambhiraopet",
        "Illanthakunta",
        "Konaraopet",
        "Mustabad",
        "Rudrangi",
        "Sircilla",
        "Thangallapalli",
        "Vemulawada",
        "Yellareddypet"
    ],
    "Rangareddy": [
        "Balapur",
        "Chevella",
        "Farooqnagar",
        "Ibrahimpatnam",
        "Kandukur",
        "Kandukur",
        "Maheswaram",
        "Moinabad",
        "Pargi",
        "Rajendra Nagar",
        "Saroor Nagar",
        "Shabad",
        "Shamirpet",
        "Shankarpalli",
        "Tandur",
        "Yacharam"
    ],
    "Sangareddy": [
        "Andole",
        "Ameenpur",
        "Bachupally",
        "Jinnaram",
        "Kandi",
        "Kohir",
        "Munpalle",
        "Narsapur",
        "Nyalkal",
        "Patancheru",
        "Pulkal",
        "Ramachandrapuram",
        "Rayakol",
        "Sadasivpet",
        "Sangareddy",
        "Sankarayalapet",
        "Toguta",
        "Zaheerabad"
    ],
    "Siddipet": [
        "Chinna Kodur",
        "Doultabad",
        "Dubbak",
        "Gajwel",
        "Husnabad",
        "Jagdevpur",
        "Kondapak",
        "Mirdoddi",
        "Mulug",
        "Nangnur",
        "Siddipet",
        "Thoguta",
        "Wargal"
    ],
    "Suryapet": [
        "Chivvemla",
        "Jajireddygudem",
        "Mellacheruvu",
        "Mothey",
        "Nadigudem",
        "Nuthankal",
        "Penpahad",
        "Suryapet",
        "Thungathurthy"
    ],
    "Vikarabad": [
        "Bantwaram",
        "Bantoor",
        "Bhoothpur",
        "Dharur",
        "Dodipatla",
        "Hassanabad",
        "Kodangal",
        "Kothapeta",
        "Marpalle",
        "Mominpet",
        "Pargi",
        "Peddemul",
        "Pudur",
        "Raikode",
        "Tandur",
        "Vikarabad",
        "Yalal"
    ],
    "Wanaparthy": [
        "Ghanpur",
        "Gopalpally",
        "Kothakota",
        "Pangal",
        "Pebbair",
        "Singotam",
        "Srirangapur",
        "Veepanagandla",
        "Wanaparthy"
    ],
    "Warangal Rural": [
        "Chennaraopet",
        "Duggondi",
        "Geevaram",
        "Khanapur",
        "Nallabelli",
        "Narsimhulapet",
        "Nellikudur",
        "Parvathagiri",
        "Raiparthi",
        "Sangem",
        "Thorrur",
        "Wardhannapet"
    ],
    "Warangal Urban": [
        "Dharmasagar",
        "Hasanparthy",
        "Kazipet",
        "Khila Warangal",
        "Warangal"
    ],
    "Yadadri Bhuvanagiri": [
        "Aler",
        "Bhongir",
        "Bhuvanagiri",
        "Bommalaramaram",
        "Choutuppal",
        "Gundala",
        "Mothey",
        "Narayanpur",
        "Rajapet",
        "Thurkapalli",
        "Yadagirigutta"
    ]
},
  "Andhra Pradesh": {
    "Alluri Sitharama Raju": [
        "Addateegala",
        "Ananthagiri",
        "Araku Valley",
        "Chintapalle",
        "Chintur",
        "Devipatnam",
        "Dumbriguda",
        "Etapaka",
        "G. Madugula",
        "Gangavaram",
        "Gudem Kotha Veedhi",
        "Gurthedu",
        "Hukumpeta",
        "Koyyuru",
        "Kunavaram",
        "Maredumilli",
        "Munchingi Puttu",
        "Paderu",
        "Peda Bayalu",
        "Rajavommangi",
        "Rampachodavaram",
        "Vararamachandrapuram",
        "Y. Ramavaram"
    ],
    "Anakapalli": [
        "Anakapalli",
        "Atchutapuram",
        "Butchayyapeta",
        "Cheedikada",
        "Chodavaram",
        "Devarapalli",
        "Elamanchili",
        "Golugonda",
        "K. Kotapadu",
        "Kasimkota",
        "Kotauratla",
        "Madugula",
        "Makavarapalem",
        "Munagapaka",
        "Nakkapalle",
        "Narsipatnam",
        "Nathavaram",
        "Paravada",
        "Payakaraopeta",
        "Rambilli",
        "Ravikamatham",
        "Rolugunta",
        "Sabbavaram",
        "Sarvasiddhi Rayavaram"
    ],
    "Anantapur": [
        "Anantapuramu",
        "Atmakur",
        "Beluguppa",
        "Bommanahal",
        "Brahmasamudram",
        "Bukkaraya Samudram",
        "D.Hirehal",
        "Garladinne",
        "Gooty",
        "Gummagatta",
        "Guntakal",
        "Kalyandurg",
        "Kambadur",
        "Kanekal",
        "Kudair",
        "Kundurpi",
        "Narpala",
        "Pamidi",
        "Peddapappur",
        "Peddavadugur",
        "Putlur",
        "Raptadu",
        "Rayadurg",
        "Settur",
        "Singanamala",
        "Tadipatri",
        "Uravakonda",
        "Vajrakarur",
        "Vidapanakal",
        "Yadiki",
        "Yellanur"
    ],
    "Annamayya": [
        "Beerangi Kothakota",
        "Chinnamandyam",
        "Chowdepalle",
        "Galiveedu",
        "Gurramkonda",
        "Kalakada",
        "Kalikiri",
        "Kambhamvaripalle",
        "Kurabalakota",
        "Lakkireddipalli",
        "Madanapalle",
        "Mulakalacheruvu",
        "Nimmanapalle",
        "Peddamandyam",
        "Peddathippasamudram",
        "Pileru",
        "Punganur",
        "Ramapuram",
        "Ramasamudram",
        "Rayachoti",
        "Sambepalli",
        "Sodam",
        "Somala",
        "Thamballapalle",
        "Vayalpad"
    ],
    "Bapatla": [
        "Amruthalur",
        "Bapatla",
        "Bhattiprolu",
        "Cherukupalle",
        "Chinaganjam",
        "Chirala",
        "Inkollu",
        "Karamchedu",
        "Karlapalem",
        "Kolluru",
        "Martur",
        "Nagaram",
        "Nizampatnam",
        "Parchur",
        "Pittalavanipalem",
        "Repalle",
        "Tsundur",
        "Vemuru",
        "Vetapalem",
        "Yeddanapudi"
    ],
    "Chittoor": [
        "Baireddipalle",
        "Bangarupalem",
        "Chittoor",
        "Chittoor Urban",
        "Gangadhara Nellore",
        "Gangavaram",
        "Gudipala",
        "Gudipalle",
        "Irala",
        "Karvetinagar",
        "Kuppam",
        "Nagari",
        "Nindra",
        "Palamaner",
        "Palasamudram",
        "Peddapanjani",
        "Penumuru",
        "Pulicherla",
        "Puthalapattu",
        "Ramakuppam",
        "Rompicherla",
        "Santhipuram",
        "Sri Rangaraja Puram",
        "Thavanampalle",
        "Vedurukuppam",
        "Venkatagirikota",
        "Vijayapuram",
        "Yadamarri"
    ],
    "Konaseema": [
        "Ainavilli",
        "Alamuru",
        "Allavaram",
        "Amalapuram",
        "Ambajipeta",
        "Atreyapuram",
        "I. Polavaram",
        "K. Gangavaram",
        "Katrenikona",
        "Kothapeta",
        "Malikipuram",
        "Mamidikuduru",
        "Mummidivaram",
        "P. Gannavaram",
        "Ramachandrapuram",
        "Ravulapalem",
        "Razole",
        "Sakhinetipalle",
        "Uppalaguptam"
    ],
    "East Godavari": [
        "Anaparthi",
        "Biccavolu",
        "Chagallu",
        "Devarapalle",
        "Gokavaram",
        "Gopalapuram",
        "Kadiam",
        "Kapileswarapuram",
        "Korukonda",
        "Kovvur",
        "Mandapeta",
        "Nallajerla",
        "Nidadavole",
        "Peravali",
        "Rajahmundry Rural",
        "Rajahmundry Urban",
        "Rajanagaram",
        "Rangampeta",
        "Rayavaram",
        "Seethanagaram",
        "Tallapudi",
        "Undrajavaram"
    ],
    "Eluru": [
        "Agiripalli",
        "Bhimadole",
        "Buttayagudem",
        "Chatrai",
        "Chintalapudi",
        "Denduluru",
        "Dwaraka Tirumala",
        "Eluru",
        "Jangareddygudem",
        "Jeelugu Milli",
        "Kaikalur",
        "Kalidindi",
        "Kamavarapukota",
        "Koyyalagudem",
        "Kukunoor",
        "Lingapalem",
        "Mandavalli",
        "Mudinepalle",
        "Musunuru",
        "Nidamarru",
        "Nuzvid",
        "Pedapadu",
        "Pedavegi",
        "Polavaram",
        "T. Narasapuram",
        "Unguturu",
        "Velairpadu"
    ],
    "Guntur": [
        "Chebrolu",
        "Duggirala",
        "Guntur East",
        "Guntur West",
        "Kakumanu",
        "Kollipara",
        "Mangalagiri",
        "Medikonduru",
        "Pedakakani",
        "Pedanandipadu",
        "Phirangipuram",
        "Ponnur",
        "Prathipadu",
        "Tadepalli",
        "Tadikonda",
        "Tenali",
        "Thullur",
        "Vatticherukuru"
    ],
    "Kakinada": [
        "Gandepalle",
        "Gollaprolu",
        "Jaggampeta",
        "Kajuluru",
        "Kakinada Rural",
        "Kakinada Urban",
        "Karapa",
        "Kirlampudi",
        "Kotananduru",
        "Kothapalle",
        "Pedapudi",
        "Peddapuram",
        "Pithapuram",
        "Prathipadu",
        "Rowthulapudi",
        "Samalkota",
        "Sankhavaram",
        "Thallarevu",
        "Thondangi",
        "Tuni",
        "Yeleswaram"
    ],
    "Krishna": [
        "Avanigadda",
        "Bantumilli",
        "Bapulapadu",
        "Challapalli",
        "Gannavaram",
        "Ghantasala",
        "Gudivada",
        "Gudlavalleru",
        "Guduru",
        "Kankipadu",
        "Koduru",
        "Kruthivennu",
        "Machilipatnam",
        "Mopidevi",
        "Movva",
        "Nagayalanka",
        "Nandivada",
        "Pamarru",
        "Pamidimukkala",
        "Pedana",
        "Pedaparupudi",
        "Penamaluru",
        "Thotlavalluru",
        "Unguturu",
        "Vuyyuru"
    ],
    "Kurnool": [
        "Adoni Rural",
        "Adoni Urban",
        "Alur",
        "Aspari",
        "C.Belagal",
        "Chippagiri",
        "Devanakonda",
        "Gonegandla",
        "Gudur",
        "Halaharvi",
        "Holagunda",
        "Kallur",
        "Kodumur",
        "Kosigi",
        "Kowthalam",
        "Krishnagiri",
        "Kurnool Rural",
        "Kurnool Urban",
        "Maddikera East",
        "Mantralayam",
        "Nandavaram",
        "Orvakal",
        "Pattikonda",
        "Pedda Kadubur",
        "Tuggali",
        "Veldurthi",
        "Yemmiganur"
    ],
    "Prakasam": [
        "Addanki",
        "Ardhaveedu",
        "Ballikurava",
        "Bestawaripeta",
        "Chandra Sekhara Puram",
        "Chimakurthi",
        "Cumbum",
        "Darsi",
        "Donakonda Kanigiri",
        "Dornala",
        "Giddalur",
        "Gudluru",
        "Hanumanthuni Padu",
        "J. Panguluru",
        "Kandukuru",
        "Kanigiri",
        "Komarolu",
        "Konakanamitla",
        "Kondapi",
        "Korisapadu",
        "Kotha Patnam",
        "Kurichedu",
        "Lingasamudram",
        "Maddipadu",
        "Markapuram",
        "Marripudi",
        "Mundlamuru Ongole",
        "Naguluppalapadu",
        "Ongole Rural",
        "Ongole Urban",
        "Pamur",
        "Peda Araveedu",
        "Pedacherlo Palle",
        "Podili",
        "Ponnaluru",
        "Pullalacheruvu",
        "Racherla",
        "Santhamaguluru",
        "Santhanuthala Padu",
        "Singarayakonda",
        "Tangutur",
        "Tarlupadu",
        "Thallur",
        "Tripuranthakam",
        "Ulavapadu",
        "Veligandla",
        "Voletivaripalem",
        "Yerragondapalem",
        "Zarugumilli"
    ],
    "NTR": [
        "A. Konduru",
        "Chandarlapadu",
        "G.Konduru",
        "Gampalagudem",
        "Ibrahimpatnam",
        "Jaggayyapeta",
        "Kanchikacherla",
        "Mylavaram",
        "Nandigama",
        "Penuganchiprolu",
        "Reddigudem",
        "Tiruvuru",
        "Vatsavai",
        "Veerullapadu",
        "Vijayawada Central",
        "Vijayawada East",
        "Vijayawada North",
        "Vijayawada Rural",
        "Vijayawada West",
        "Vissannapeta"
    ],
    "Nandyal": [
        "Allagadda",
        "Atmakur",
        "Banaganapalle",
        "Bandi Atmakur",
        "Bethamcherla",
        "Chagalamarri",
        "Dhone",
        "Dornipadu",
        "Gadivemula",
        "Gospadu",
        "Jupadu Bungalow",
        "Koilkuntla",
        "Kolimigundla",
        "Kothapalle",
        "Mahanandi",
        "Midthuru",
        "Nandikotkur",
        "Nandyal Rural",
        "Nandyal Urban",
        "Owk",
        "Pagidyala",
        "Pamulapadu",
        "Panyam",
        "Peapally",
        "Rudravaram",
        "Sanjamala",
        "Sirivella",
        "Srisailam",
        "Uyyalawada",
        "Velgodu"
    ],
    "Palnadu": [
        "Amaravathi",
        "Atchampet",
        "Bellamkonda",
        "Bollapalle",
        "Chilakaluripet",
        "Dachepalle",
        "Durgi",
        "Edlapadu",
        "Gurazala",
        "Ipuru",
        "Karempudi",
        "Krosuru",
        "Machavaram",
        "Macherla",
        "Muppalla",
        "Nadendla",
        "Narasaraopet",
        "Nekarikallu",
        "Nuzendla",
        "Pedakurapadu",
        "Piduguralla",
        "Rajupalem",
        "Rentachintala",
        "Rompicherla",
        "Sattenapalle",
        "Savalyapuram",
        "Veldurthi",
        "Vinukonda"
    ],
    "Parvathipuram Manyam": [
        "Balijipeta",
        "Bhamini",
        "Garugubilli",
        "Gummalakshmipuram",
        "Jiyyammavalasa",
        "Komarada",
        "Kurupam",
        "Makkuva",
        "Pachipenta",
        "Palakonda",
        "Parvathipuram",
        "Salur",
        "Seethampeta",
        "Seethanagaram",
        "Veeraghattam"
    ],
    "SPSR Nellore": [
        "Allur",
        "Ananthasagaram",
        "Anumasamudrampeta",
        "Atmakur",
        "Bogolu",
        "Buchireddypalem",
        "Chejerla",
        "Chillakur",
        "Dagadarthi",
        "Duttaluru",
        "Gudur",
        "Indukurpet",
        "Jaladanki",
        "Kaligiri",
        "Kaluvoya",
        "Kavali",
        "Kodavaluru",
        "Kota",
        "Kovur",
        "Manubolu",
        "Marripadu",
        "Muttukuru",
        "Nellore Rural",
        "Nellore Urban",
        "Podalakuru",
        "Rapuru",
        "Saidapuramu",
        "Sangam",
        "Sitarampuramu",
        "Thotapalligudur",
        "Udayagiri",
        "Venkatachalam",
        "Vidavaluru",
        "Vinjamuru"
    ],
    "Sri Sathya Sai": [
        "Agali",
        "Amadagur",
        "Amarapuram",
        "Bathalapalle",
        "Bukkapatnam",
        "Chennekothapalle",
        "Chilamathur",
        "Dharmavaram",
        "Gandlapenta",
        "Gorantla",
        "Gudibanda",
        "Hindupur",
        "Kadiri",
        "Kanaganapalle",
        "Kothacheruvu",
        "Lepakshi",
        "Madakasira",
        "Mudigubba",
        "Nallacheruvu",
        "Nallamada",
        "Nambulapulakunta",
        "Obuladevaracheruvu",
        "Parigi",
        "Penukonda",
        "Puttaparthi",
        "Ramagiri",
        "Roddam",
        "Rolla",
        "Somandepalle",
        "Tadimarri",
        "Talupula",
        "Tanakal"
    ],
    "Srikakulam": [
        "Amadalavalasa",
        "Burja",
        "Etcherla",
        "Ganguvarisigadam",
        "Gara",
        "Hiramandalam",
        "Ichchapuram",
        "Jalumuru",
        "Kanchili",
        "Kaviti",
        "Kotabommali",
        "Kothuru",
        "Lakshminarsupeta",
        "Laveru",
        "Mandasa",
        "Meliaputti",
        "Nandigam",
        "Narasannapeta",
        "Palasa",
        "Pathapatnam",
        "Polaki",
        "Ponduru",
        "Ranastalam",
        "Santhabommali",
        "Saravakota",
        "Sarubujjili",
        "Sompeta",
        "Srikakulam",
        "Tekkali",
        "Vajrapukothuru"
    ],
    "Tirupati": [
        "Balayapalle",
        "Buchinaidu Kandriga",
        "Chandragiri",
        "Chinnagottigallu",
        "Chittamur",
        "Chitvel",
        "Dakkili",
        "Doravarisatram",
        "K. V. B. Puram",
        "Kodur",
        "Nagalapuram",
        "Naidupeta",
        "Narayanavanam",
        "Obulavaripalle",
        "Ozili",
        "Pakala",
        "Pellakur",
        "Penagalur",
        "Pichatur",
        "Pullampeta",
        "Puttur",
        "Ramachandrapuram",
        "Renigunta",
        "Satyavedu",
        "Srikalahasti",
        "Sullurpeta",
        "Tada",
        "Thottambedu",
        "Tirupati Rural",
        "Tirupati Urban",
        "Vadamalapeta",
        "Vakadu",
        "Varadaiahpalem",
        "Venkatagiri",
        "Yerpedu",
        "Yerravaripalem"
    ],
    "Visakhapatnam": [
        "Anandapuram",
        "Bheemunipatnam",
        "Gajuwaka",
        "Gopalapatnam",
        "Maharanipeta",
        "Mulagada",
        "Padmanabham",
        "Pedagantyada",
        "Pendurthi",
        "Seethammadhara",
        "Visakhapatnam Rural"
    ],
    "Vizianagaram": [
        "Badangi",
        "Bhogapuram",
        "Bobbili",
        "Bondapalle",
        "Cheepurupalle",
        "Dattirajeru",
        "Denkada",
        "Gajapathinagaram",
        "Gantyada",
        "Garividi",
        "Gurla",
        "Jami",
        "Kothavalasa",
        "Lakkavarapukota",
        "Mentada",
        "Merakamudidam",
        "Nellimarla",
        "Pusapatirega",
        "Rajam",
        "Ramabhadrapuram",
        "Regidi Amadalavalasa",
        "Santhakaviti",
        "Srungavarapukota",
        "Therlam",
        "Vangara",
        "Vepada",
        "Vizianagaram"
    ],
    "West Godavari": [
        "Achanta",
        "Akividu",
        "Attili",
        "Bhimavaram",
        "Ganapavaram",
        "Iragavaram",
        "Kalla",
        "Mogalthur",
        "Palacoderu",
        "Palakollu",
        "Pentapadu",
        "Penugonda",
        "Penumantra",
        "Poduru",
        "Tadepalligudem",
        "Tanuku",
        "Undi",
        "Veeravasaram",
        "Yelamanchili"
    ],
    "YSR Kadapa": [
        "Atlur",
        "B. Kodur",
        "Badvel",
        "Brahmamgarimattam",
        "Chakrayapet",
        "Chapad",
        "Chennur",
        "Chinthakommadinne",
        "Duvvur",
        "Gopavaram",
        "Jammalamadugu",
        "Kadapa",
        "Kalasapadu",
        "Kamalapuram",
        "Khajipet",
        "Kondapuram",
        "Lingala",
        "Muddanur",
        "Mylavaram",
        "Nandalur",
        "Peddamudium",
        "Pendlimarri",
        "Porumamilla",
        "Proddatur",
        "Pulivendla",
        "Rajampet",
        "Rajupalem",
        "S.Mydukur",
        "Sidhout",
        "Simhadripuram",
        "Sri Avadhutha Kasinayana",
        "T. Sundupalle",
        "Thondur",
        "Vallur",
        "Veeraballi",
        "Veerapunayunipalle",
        "Vempalle",
        "Vemula",
        "Vontimitta",
        "Yerraguntla"
    ]
}
};
